# Generated by Django 4.2 on 2023-04-21 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catlist', '0003_catlist_catlistname'),
        ('catlog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catlog',
            name='catLogName',
            field=models.ForeignKey(default='Unknown', on_delete=django.db.models.deletion.CASCADE, parent_link=True, related_name='catlog_ptr', to='catlist.catlist', to_field='catListName'),
        ),
    ]
