# Generated by Django 4.2 on 2023-04-21 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catlist', '0002_remove_catlist_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='catlist',
            name='catListName',
            field=models.CharField(default='Unknown', max_length=16, unique=True),
        ),
    ]
